microserviceName: app
microservicePort: "8000"
microserviceVersion: 1.0.0
environment: dev
workspaceFolder: ./workspace

log:
  level: info

database:
  host: localhost
  port: "5432"
  user: testdb
  password: testdb123
  dbName: postgres
  sslMode: disable
