version: '3.9'

services:
  postgres-db:
    image: postgis/postgis:16-3.4-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: testdb
      POSTGRES_PASSWORD: testdb123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
